### ISSUE TITLE
leddisplay documentation

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/library-documentation#3]
The leddisplay library is part of the TcMenu documentation. We should either remove it from the docs or move this library into the TcMenu organization.

https://github.com/davetcc/leddisplay

**Comment by davetcc** [comment]
agreed let's just remove, it is a legacy library that is not used often

**Comment by vzahradnik** [comment]
Removed in e16fe8ad10a32649a12d2ba7200df1ed35bca158.
